export type RecordItem={id:string;type:string;name:string;parentId:string|null;department:string;owner:string;description:string;fields:Record<string,any>;links:string[];archived:boolean;version:number};
export const departments=['Hasar Yönetimi','Mali İşler','Hukuk','Bilgi Teknolojileri','İnsan Kaynakları','Satın Alma','İdari İşler','Raporlama','Risk Yönetimi','İç Kontrol'];
export const roles=['Çalışan','Süreç Sahibi','Birim Yöneticisi','İç Kontrol','Risk Yönetimi','İç Denetim','Üst Yönetim','Sistem Yöneticisi'];
export const types=['Ana süreç','Alt süreç','Faaliyet','İş adımı','Risk','Kontrol','Aksiyon','Doküman','KRI'];
export const baseFields:Record<string,string[]>={
'Ana süreç':['Amaç','Olgunluk','Son gözden geçirme','Sonraki gözden geçirme'],
'Alt süreç':['Amaç','Son gözden geçirme','Sonraki gözden geçirme'],
'Faaliyet':['Amaç','Girdi','Çıktı'],
'İş adımı':['Amaç','Görevliler','Kullanılan sistem','Girdi','Çıktı','Önceki adım','Sonraki adım','Prosedür','Kritik nokta','Örnek'],
'Risk':['Neden','Sonuç','Kategori','Olasılık','Etki','Doğal risk','Artık olasılık','Artık etki','Artık risk','Risk iştahı','Değerlendirme tarihi'],
'Kontrol':['Tür','Uygulama','Sıklık','Kanıt','Yöntem','Son uygulanma','Etkinlik'],
'Aksiyon':['Hedef tarih','Öncelik','Durum','Tamamlanma','Kanıt','Yönetici yorumu'],
'Doküman':['Tür','İçerik','Yayın tarihi','Son güncelleme','Sonraki gözden geçirme','Dosya bağlantısı'],
'KRI':['Değer','Yeşil üst sınır','Sarı üst sınır','Birim','Ölçüm tarihi']};
const steps=[
['Hasar İhbarı','Hasar bildirimini zamanında ve doğru bilgilerle kaydetmek.','Hasar Operasyon Uzmanı','Eksik ihbar bilgisi','Geç ihbar kaydı','Zorunlu alan doğrulaması','İhbar süre takibi','İhbar tarihi ve poliçe numarası doğrulanmalıdır.','Sigortalı olay tarihini eksik ilettiğinde başvuru tamamlanmadan doğrulama yapılır.'],
['Dosya Açılışı','Poliçe ve sigortalı bilgilerini eşleştirerek tekil hasar dosyası oluşturmak.','Hasar Dosya Uzmanı','Mükerrer dosya açılması','Yanlış poliçe eşleşmesi','Mükerrer dosya kontrolü','Poliçe kimlik eşleştirmesi','Aynı olaya ait dosyalar birleştirilmeden ödeme yapılmamalıdır.','Aynı kazanın acente ve çağrı merkezinden bildirilmesi tekil olay numarasıyla yakalanır.'],
['Evrak Kontrolü','Talep edilen belgelerin tamlığını ve geçerliliğini doğrulamak.','Hasar Evrak Uzmanı','Eksik belge ile işlem','Sahte belge kabulü','Belge tamlık listesi','Belge doğrulama','Kişisel veriler yalnızca yetkili kişilerce görülmelidir.','Eksik kaza tutanağı olan dosya değerlendirmeye alınmadan tamamlatılır.'],
['Eksper Atama','Uygun uzmanlık ve bağımsızlığa sahip eksperi atamak.','Eksper Koordinatörü','Çıkar çatışması','Uygun olmayan eksper','Bağımsızlık beyanı','Yetkinlik kontrolü','Eksper ile hak sahibi arasındaki ilişki kontrol edilmelidir.','Tedarikçiyle ilişkisi bulunan eksper yerine bağımsız eksper atanır.'],
['Hasar Değerlendirmesi','Hasarın teminat kapsamını ve tazmin edilebilirliğini değerlendirmek.','Hasar Değerlendirme Uzmanı','Teminat dışı hasarın kabulü','Hatalı hasar değerlendirmesi','Teminat uygunluk kontrolü','İkinci uzman incelemesi','İstisna hükümleri gerekçeli olarak değerlendirilmelidir.','Poliçe kapsamı dışındaki olay için ödeme önerisi ikinci incelemede durdurulur.'],
['Tazminat Hesaplama','Muafiyet, limit ve hasar tutarına göre tazminatı hesaplamak.','Tazminat Uzmanı','Hatalı muafiyet hesabı','Limit üstü tazminat','Otomatik hesap doğrulaması','Limit kontrolü','Muafiyet ve döviz kuru tarihi doğrulanmalıdır.','Yüzde on muafiyetin uygulanmadığı hesap bağımsız hesaplama ile düzeltilir.'],
['Ödeme Onayı','Ödemeyi tutara uygun yetki ve görevler ayrılığı ile onaylamak.','Hasar Birim Yöneticisi','Yetkisiz ödeme onayı','Görevler ayrılığı ihlali','Yetki limiti kontrolü','Çift onay','Hazırlayan ve onaylayan aynı kişi olamaz.','Yetki limitini aşan dosya bir üst onay seviyesine yönlendirilir.'],
['Muhasebeleştirme','Tazminat kaydını doğru hesap ve döneme işlemek.','Muhasebe Uzmanı','Yanlış hesap kodu','Dönemsellik hatası','Hesap eşleştirme','Dönem mutabakatı','Ödeme kaydı ile muhasebe kaydı uzlaştırılmalıdır.','Ay sonunda yanlış döneme atılan kayıt mutabakatta belirlenir.'],
['Ödeme','Onaylı tazminatı doğrulanmış hak sahibine aktarmak.','Hazine Uzmanı','Yanlış IBAN ile ödeme','Mükerrer ödeme','IBAN hak sahibi eşleştirmesi','Tekil ödeme referansı','IBAN değişiklikleri ayrı bir kanaldan doğrulanmalıdır.','Yanlış IBAN girilmesi: hak sahibi eşleşmesi başarısız olur; ödeme durdurulur ve doğrulama kaydı saklanır.'],
['Dosya Kapatma','Tüm ödeme, kanıt ve onayları tamamlanan dosyayı arşivlemek.','Hasar Dosya Uzmanı','Eksik kanıtla kapanış','Yetkisiz arşiv erişimi','Kapanış kontrol listesi','Arşiv erişim kontrolü','Saklama süreleri ve erişim yetkileri gözden geçirilmelidir.','Ödeme dekontu eksik dosya kapanış kontrolünden geçemez.']];
export function seedRecords():RecordItem[]{const out:RecordItem[]=[];function add(id:string,type:string,name:string,parentId:string|null,owner:string,description:string,fields:Record<string,any>={},links:string[]=[]){out.push({id,type,name,parentId,owner,description,fields,links,department:'Hasar Yönetimi',archived:false,version:1})}
 departments.forEach((d,i)=>{add('p'+i,'Ana süreç',d,null,i===0?'Hasar Birim Yöneticisi':'Atanacak',i===0?'Hasar ihbarından dosya kapanışına uçtan uca yönetim.':'Süreç tanımları için hazır alan.',{'Olgunluk':i===0?'3 / 5':'Tanımlanmadı','Son gözden geçirme':'2026-03-01','Sonraki gözden geçirme':'2027-03-01'});out[out.length-1].department=d});
 add('sub0','Alt süreç','Hasar dosyası yönetimi','p0','Hasar Birim Yöneticisi','Hasar dosyasının tüm yaşam döngüsü.');
 add('act0','Faaliyet','Hasar talebinin sonuçlandırılması','sub0','Hasar Operasyon Ekibi','İhbar, inceleme, değerlendirme ve ödeme faaliyetleri.');
 steps.forEach(([name,desc,owner,r1,r2,c1,c2,critical,example],i)=>{const id='s'+i;add(id,'İş adımı',name,'act0',owner,desc,{'Amaç':desc,'Görevliler':owner,'Kullanılan sistem':'Hasar Yönetim Sistemi','Girdi':i?steps[i-1][0]+' çıktısı':'Sigortalı hasar bildirimi','Çıktı':name+' işlem kaydı','Önceki adım':i?steps[i-1][0]:'Başlangıç','Sonraki adım':steps[i+1]?.[0]||'Bitiş','Prosedür':'PR-HSR-'+String(i+1).padStart(2,'0'),'Kritik nokta':critical,'Örnek':example},['r'+i+'a','r'+i+'b','c'+i+'a','c'+i+'b','d'+i,'a'+i]);
 [r1,r2].forEach((r,j)=>{const suffix=j?'b':'a';const prob=2+(i+j)%3;const impact=i>=5?5:3+(i%2);add('r'+i+suffix,'Risk',r,id,owner,r+' nedeniyle sürecin amaçlanan sonucuna ulaşılamaması.',{'Neden':j?'Yetki veya sistem kuralının yetersizliği':'Eksik doğrulama ve insan hatası','Sonuç':i>=5?'Hatalı ödeme ve finansal kayıp':'İşlem gecikmesi ve operasyonel kayıp','Kategori':i>=5?'Finansal Risk':'Operasyonel Risk','Olasılık':prob,'Etki':impact,'Doğal risk':prob*impact,'Artık olasılık':Math.max(1,prob-1),'Artık etki':impact,'Artık risk':Math.max(1,prob-1)*impact,'Risk iştahı':6,'Değerlendirme tarihi':'2026-09-05'},['c'+i+suffix,'a'+i])});
 [c1,c2].forEach((c,j)=>{const suffix=j?'b':'a';add('c'+i+suffix,'Kontrol',c,id,owner,c+' sonucunu kanıtla kayıt altına almak.',{'Tür':j?'Tespit edici':'Önleyici','Uygulama':j?'Manuel':'Otomatik','Sıklık':'Her işlemde','Kanıt':c+' kontrol kaydı','Yöntem':j?'Bağımsız inceleme ve mutabakat':'Sistem kuralı ile doğrulama','Son uygulanma':'2026-09-04','Etkinlik':i===8&&j?'Geliştirilmeli':'Etkin'},['r'+i+suffix])});
 add('d'+i,'Doküman',name+' prosedürü',id,owner,'PR-HSR-'+String(i+1).padStart(2,'0'),{'Tür':'Prosedür','İçerik':desc+'\n1. Girdileri doğrula.\n2. '+c1+' uygula.\n3. '+c2+' sonucunu kaydet.\n4. '+critical+'\n5. Kontrol kanıtını dosyaya bağla.','Yayın tarihi':'2026-03-01','Son güncelleme':'2026-08-01','Sonraki gözden geçirme':'2027-03-01'},['c'+i+'a','c'+i+'b']);
 add('a'+i,'Aksiyon',c1+' geliştirmesi',id,owner,'Kontrol kapsamını örnek dosyalarla gözden geçir ve kanıtı kaydet.',{'Hedef tarih':i<2?'2026-09-01':'2026-10-15','Öncelik':i>=6?'Yüksek':'Orta','Durum':i%2?'Devam ediyor':'Açık','Tamamlanma':i%2?40:0,'Kanıt':'','Yönetici yorumu':''},['r'+i+'a','c'+i+'a']);});
 add('kri0','KRI','30 günü aşan açık dosya oranı','p0','Hasar Birim Yöneticisi','Örnek ölçüm; gerçek sistem bağlantısı henüz kurulmadı.',{'Değer':8,'Yeşil üst sınır':5,'Sarı üst sınır':10,'Birim':'%','Ölçüm tarihi':'2026-09-05'},['r8a']);return out;}
export function riskLevel(score:number,critical=20){return score>=critical?'Kritik':score>=12?'Yüksek':score>=6?'Orta':'Düşük'}
