import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {seedRecords,roles,types,RecordItem} from '@/lib/model';
export const dynamic='force-dynamic';
const defaultPermissions:Record<string,string[]>={'Çalışan':['read'],'Süreç Sahibi':['read','edit_own'],'Birim Yöneticisi':['read','edit_department','approve_manager'],'İç Kontrol':['read','edit','approve_control'],'Risk Yönetimi':['read','edit','approve_control'],'İç Denetim':['read'],'Üst Yönetim':['read'],'Sistem Yöneticisi':['read','edit','approve_manager','approve_control','admin']};
function initial(){return {records:seedRecords(),members:[],roles:defaultPermissions,requests:[],audit:[],parameters:{reviewMonths:12,criticalScore:20},notifications:[]}}
async function load(){const db=env.DB;await db.prepare('INSERT OR IGNORE INTO workspace (id,revision,data) VALUES (?,1,?)').bind('main',JSON.stringify(initial())).run();const row=await db.prepare('SELECT revision,data FROM workspace WHERE id=?').bind('main').first<any>();return {revision:row.revision,state:JSON.parse(row.data)}}
function fail(message:string,status=400){return Response.json({error:message},{status})}
function permitted(state:any,user:any){return state.members.find((m:any)=>m.email.toLowerCase()===user.email.toLowerCase()&&m.active!==false)}
function perms(s:any,m:any){return m?(s.roles[m.role]||[]):[]}
function canEdit(s:any,m:any,r:any){const p=perms(s,m);return p.includes('admin')||p.includes('edit')||p.includes('edit_department')&&r.department===m.department||p.includes('edit_own')&&r.owner===m.name}
export async function GET(){try{const user=await getChatGPTUser();if(!user)return fail('Giriş yapmalısınız.',401);const {revision,state}=await load();const member=permitted(state,user);const ownerEmail=(env as any).OWNER_EMAIL;const bootstrap=state.members.length===0&&ownerEmail&&user.email.toLowerCase()===ownerEmail.toLowerCase();if(!member&&!bootstrap)return Response.json({user,revision,demo:true,records:seedRecords(),member:null,roles:{},requests:[],audit:[],parameters:{},notifications:[],members:[]});return Response.json({...state,user,member,revision,bootstrap:!!bootstrap,demo:false,permissions:perms(state,member)})}catch{return fail('Çalışma alanı yüklenemedi. Lütfen tekrar deneyin.',503)}}
export async function POST(request:Request){try{const user=await getChatGPTUser();if(!user)return fail('Giriş yapmalısınız.',401);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return fail('Geçersiz istek kaynağı.',403);const raw=await request.text();if(raw.length>2000000)return fail('İstek çok büyük.',413);const body=JSON.parse(raw);const {revision,state:s}=await load();if(body.revision!==revision)return fail('Başka bir kullanıcı kayıtları güncelledi. Yenileyip tekrar deneyin.',409);let m=permitted(s,user);const p=perms(s,m);const isAdmin=p.includes('admin');const now=new Date().toISOString();let before:any=null,after:any=null,target='';
 if(body.action==='bootstrap'){const ownerEmail=(env as any).OWNER_EMAIL;if(s.members.length||!ownerEmail||user.email.toLowerCase()!==ownerEmail.toLowerCase())return fail('Yönetici kurulumu için yetkiniz yok.',403);m={id:crypto.randomUUID(),email:user.email,name:user.displayName,department:'İç Kontrol',unit:'İç Kontrol',position:'Müdür',manager:'',role:'Sistem Yöneticisi',active:true};s.members.push(m);after=m;target=m.id}
 else{if(!m)return fail('Çalışma alanı üyeliğiniz bulunmuyor.',403);
 if(['save','archive'].includes(body.action)){const r=body.record as RecordItem;const old=s.records.find((x:any)=>x.id===r?.id);if(!r||!types.includes(r.type)||typeof r.name!=='string'||!r.name.trim()||r.name.length>300||!r.fields||typeof r.fields!=='object'||!Array.isArray(r.links))return fail('Kayıt alanlarını kontrol edin.');if(old&&!canEdit(s,m,old)||!old&&!canEdit(s,m,r))return fail('Bu kayıt için düzenleme yetkiniz yok.',403);if(r.parentId&&!s.records.some((x:any)=>x.id===r.parentId&&!x.archived))return fail('Geçerli bir üst kayıt seçin.');let ancestor=r.parentId;const visited=new Set([r.id]);while(ancestor){if(visited.has(ancestor))return fail('Döngü oluşturan üst kayıt seçilemez.');visited.add(ancestor);ancestor=s.records.find((x:any)=>x.id===ancestor)?.parentId}if(r.links.some(id=>!s.records.some((x:any)=>x.id===id)))return fail('Bağlantılı kayıt bulunamadı.');if(r.type==='Risk'){for(const key of ['Olasılık','Etki','Artık olasılık','Artık etki'])if(!Number.isInteger(Number(r.fields[key]))||Number(r.fields[key])<1||Number(r.fields[key])>5)return fail('Risk olasılık ve etkisi 1–5 olmalıdır.');r.fields['Doğal risk']=Number(r.fields['Olasılık'])*Number(r.fields['Etki']);r.fields['Artık risk']=Number(r.fields['Artık olasılık'])*Number(r.fields['Artık etki'])}if(r.type==='Aksiyon'&&(Number(r.fields.Tamamlanma)<0||Number(r.fields.Tamamlanma)>100))return fail('Tamamlanma 0–100 olmalıdır.');if(old&&r.version!==old.version)return fail('Kayıt sürümü değişti.',409);before=old||null;after={...r,id:old?.id||crypto.randomUUID(),name:r.name.trim(),archived:body.action==='archive'?true:!!r.archived,version:(old?.version||0)+1};target=after.id;if((body.action==='archive'||old&&old.archived!==r.archived)&&!isAdmin)return fail('Arşivleme için yönetici yetkisi gerekir.',403);const critical=body.critical||body.action==='archive'||['Risk','Kontrol'].includes(r.type);if(critical){s.requests.push({id:crypto.randomUUID(),record:after,oldVersion:old?.version||0,requester:user.email,reason:body.reason,status:'Yönetici onayı',created:now,approvals:[]});after={request:after,status:'Yönetici onayı'}}else{s.records=old?s.records.map((x:any)=>x.id===old.id?after:x):[...s.records,after]}}
 else if(body.action==='approve'||body.action==='reject'){const q=s.requests.find((x:any)=>x.id===body.id);if(!q||!['Yönetici onayı','Kontrol onayı'].includes(q.status))return fail('Onay talebi bulunamadı.');if(q.requester===user.email)return fail('Kendi talebinizi onaylayamazsınız.',403);const needed=q.status==='Yönetici onayı'?'approve_manager':'approve_control';if(!p.includes(needed))return fail('Bu aşamada onay yetkiniz yok.',403);if(q.approvals.some((a:any)=>a.email===user.email))return fail('İki onay aşamasını farklı kişiler tamamlamalıdır.',403);if(needed==='approve_manager'&&!isAdmin&&m.department!==q.record.department)return fail('Birim kapsamı dışında onay verilemez.',403);before=JSON.parse(JSON.stringify(q));target=q.id;if(body.action==='reject'){q.status='Reddedildi'}else{q.approvals.push({email:user.email,date:now});if(q.status==='Yönetici onayı')q.status='Kontrol onayı';else{const existing=s.records.find((r:any)=>r.id===q.record.id);if((existing?.version||0)!==q.oldVersion)return fail('Kayıt değişti; yeni talep oluşturulmalıdır.',409);s.records=existing?s.records.map((r:any)=>r.id===q.record.id?q.record:r):[...s.records,q.record];q.status='Onaylandı'}}after=q}
 else if(body.action==='member'){if(!isAdmin)return fail('Yönetici yetkisi gerekir.',403);const v=body.member;if(!v||!/^\S+@\S+\.\S+$/.test(v.email)||!s.roles[v.role])return fail('E-posta ve rolü kontrol edin.');const old=s.members.find((x:any)=>x.id===v.id);if(s.members.some((x:any)=>x.email.toLowerCase()===v.email.toLowerCase()&&x.id!==v.id))return fail('Bu e-posta zaten tanımlı.');if(old?.role==='Sistem Yöneticisi'&&(v.role!=='Sistem Yöneticisi'||v.active===false)&&s.members.filter((x:any)=>x.role==='Sistem Yöneticisi'&&x.active!==false).length<=1)return fail('Son sistem yöneticisi kaldırılamaz.');before=old||null;after={...v,id:old?.id||crypto.randomUUID()};target=after.id;s.members=old?s.members.map((x:any)=>x.id===old.id?after:x):[...s.members,after]}
 else if(body.action==='role'){if(!isAdmin)return fail('Yönetici yetkisi gerekir.',403);if(roles.includes(body.name))return fail('Yerleşik roller değiştirilemez; yeni rol tanımlayın.');const allowed=['read','edit_own','edit_department','edit','approve_manager','approve_control'];if(typeof body.name!=='string'||!body.name.trim()||!Array.isArray(body.permissions)||body.permissions.some((v:any)=>!allowed.includes(v)))return fail('Rol alanları geçersiz.');target=body.name;before=s.roles[target]||null;after=body.permissions;s.roles[target]=after}
 else if(body.action==='parameters'){if(!isAdmin)return fail('Yönetici yetkisi gerekir.',403);if(!Number.isInteger(body.parameters?.reviewMonths)||body.parameters.reviewMonths<1||body.parameters.reviewMonths>120||!Number.isInteger(body.parameters?.criticalScore)||body.parameters.criticalScore<13||body.parameters.criticalScore>25)return fail('Parametre aralıklarını kontrol edin.');before=s.parameters;after=body.parameters;target='parameters';s.parameters=after}
 else if(body.action==='notification'){if(!isAdmin)return fail('Yönetici yetkisi gerekir.',403);after={id:crypto.randomUUID(),text:String(body.text||'').slice(0,2000),date:now};s.notifications.push(after);target=after.id}
 else return fail('Bilinmeyen işlem.');}
 if(!body.reason||typeof body.reason!=='string')return fail('Değişiklik gerekçesi zorunludur.');s.audit.push({id:crypto.randomUUID(),actor:user.email,date:now,action:body.action,target,reason:body.reason,before,after});const result=await env.DB.prepare('UPDATE workspace SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(s),'main',revision).run();if(!result.meta.changes)return fail('Eş zamanlı değişiklik nedeniyle kaydedilemedi. Yenileyin.',409);return Response.json({ok:true});}catch{return fail('İşlem tamamlanamadı. Alanları kontrol edip tekrar deneyin.',500)}}
